---
version: "3.3"
services:

  nginx-proxy:
    image: jwilder/nginx-proxy:${JWILDER_VERSION}
    hostname: nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/config/htpasswd:/etc/nginx/htpasswd:rw
    networks:
      - tick_net

  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    hostname: influxdb
    container_name: ${CONTAINER_NAMESPACE}influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb:rw
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      VIRTUAL_HOST: ${INFLUXDB_HOST}
      VIRTUAL_PORT: 8086
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}influxdb
      tick_net:

  chronograf: 
    image: chronograf:${CHRONOGRAF_VERSION} 
    hostname: chronograf
    container_name: chronograf
    restart: always
    ports:
      - 8888
    volumes:
      - ./volumes/chronograf/:/var/lib/chronograf/:rw
    networks:
      - tick_net
    environment:
      INFLUXDB_URL: http://${CONTAINER_NAMESPACE}influxdb:8086
      KAPACITOR_URL: http://${CONTAINER_NAMESPACE}kapacitor:9092
      KAPACITOR_USERNAME: ${INFLUXDB_ADMIN_USER}
      KAPACITOR_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_USERNAME: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      VIRTUAL_HOST: ${CHRONOGRAF_HOST}
      VIRTUAL_PORT: 8888
    depends_on: 
      - influxdb
      - kapacitor
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}chronograf
      tick_net:

  kapacitor:
    image: kapacitor:${KAPACITOR_VERSION}
    hostname: kapacitor
    container_name: ${CONTAINER_NAMESPACE}kapacitor
    restart: always
    ports:
      - 9092
    environment:
      VIRTUAL_HOST: ${KAPACITOR_HOST}
      VIRTUAL_PORT: 9092
    volumes: 
      - ./volumes/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./volumes/kapacitor:/var/lib/kapacitor:rw
    depends_on:
      - influxdb
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}kapacitor
      tick_net:

networks:
  tick_net:
