---
version: "3.3"
services:

  telegraf:
    image: telegraf:latest
    restart: always
    hostname: telegraf
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    networks:
      - tick-net

  influxdb:
    image: influxdb:latest
    hostname: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./volumes/influxdb/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    networks:
      - tick-net

  chronograf:
    image: chronograf:latest
    hostname: chronograf
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./volumes/chronograf/:/var/lib/chronograf/
    networks:
      - tick-net
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092

  kapacitor:
    image: kapacitor:latest
    hostname: kapacitor
    restart: always
    ports:
      - 9092:9092
    volumes: 
      - ./conf/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
      - ./volumes/kapacitor/:/var/lib/kapacitor/
    networks:
      - tick-net

networks:
  tick-net:
    driver: bridge
