---
version: "3.3"
services:

  telegraf:
    image: telegraf:${TELEGRAF_VERSION}
    restart: always
    hostname: telegraf
    container_name: ${CONTAINER_NAMESPACE}telegraf
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    networks:
      - tick_net

networks:
  tick_net:
