version: "3.3"
services:

  telegraf:
    image: telegraf:latest
    restart: always
    hostname: telegraf
    container_name: tick-telegraf
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    networks:
      - tick-net

networks:
  tick-net:
    driver: bridge
